[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"

# 微信小程序配置
[default.wechat]
app_id = "wx2078fa60851884ca"
app_secret = "b6727ca843ad05db752c1349ebcad8c9"

[default.limits]
forms = 32768

[default.databases]
database_url = "host=192.168.5.222 port=5432 user=user_ck password=ck320621 dbname=postgres"

[default.cache]
redis_url = "redis://:ck320621@192.168.5.222:6379"

# Note: These are default configurations. For production, set environment variables:
# DATABASE_URL and REDIS_URL will override these values when set

[development]
address = "0.0.0.0"
port = 8000
log_level = "debug"

[production]
address = "0.0.0.0"
port = 8000
log_level = "normal"