[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"

[default.limits]
forms = 32768

[default.databases]
database_url = "host=192.168.5.222 port=5432 user=user_ck password=ck320621 dbname=postgres"

[default.cache]
redis_url = "redis://:ck320621@192.168.5.222:6379"

[development]
address = "0.0.0.0"
port = 8000
log_level = "debug"

[production]
address = "0.0.0.0"
port = 8000
log_level = "normal"