[default]
address = "0.0.0.0"
port = 8000
log_level = "normal"

[default.limits]
forms = 32768

[development]
address = "0.0.0.0"
port = 8000
log_level = "debug"

[production]
address = "0.0.0.0"
port = 8000
log_level = "normal"